name: Java CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: start-measurement

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: get-measurement
          label: 'repo checkout'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile Java code with Maven
        run: mvn clean compile


      - name: Excecute test
        run: |
          mvn test


      - name: Build Docker image
        run: |
          docker build -t arl-to-drl-java .
          docker images

      - name: Push Docker image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: arl-to-drl-java-001

      - name: Deploy to Docker
        uses: docker/metadata-action@v3
        with:
          images: arl-to-drl-java:arl-to-drl-java-001


      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: display-results